### ISSUE TITLE
Zarf Big Bang extension doesn't support branches

### ISSUE THREAD

**Issue by runyontr** [zarf-dev/zarf#1370]
When moving repos, zarf can't support moving a branch over in the same way that it supports pinning to a tag or a git commit.

**Comment by dgershman** [comment]
> > When moving repos, zarf can't support moving a branch over in the same way that it supports pinning to a tag or a git commit.
> 
> Have you been able to get commits to work? I haven't been able to.

Nevermind, this is a limitation of the `bigbang` extension.

**Comment by dgershman** [comment]
> > > When moving repos, zarf can't support moving a branch over in the same way that it supports pinning to a tag or a git commit.
> > 
> > 
> > Have you been able to get commits to work? I haven't been able to.
> 
> Nevermind, this is a limitation of the `bigbang` extension.

Actually it looks like a limitation of pulling Charts, it's restricted to tags.

**Comment by dgershman** [comment]
I was able to work around this by setting the `version` as `refs/heads/<branchname>`

**Comment by dgershman** [comment]
Eventually this falls when flux gets confused about the reference.  

```
couldn't find remote ref \"refs/tags/refs/heads/master\
```

**Comment by Racer159** [comment]
@dgershman the issue you were seeing was fixed in https://github.com/defenseunicorns/zarf/pull/1613 correct?

(also git branch support was added in https://github.com/defenseunicorns/zarf/releases/tag/v0.25.0)

**Comment by dgershman** [comment]
#1613 did not fix the issue.  I worked around no branch support by forking BB from Github and then using `repo` and a tag I cut myself.  Branches do not seem to work for me.

**Comment by dgershman** [comment]
This was in preparation for the `2.0.0` tag coming soon on BB.  Here is my draft PR https://github.com/defenseunicorns/zarf/pull/1611.

From: Danny Gershman ***@***.***>
Date: Tuesday, April 18, 2023 at 10:01 PM
To: defenseunicorns/zarf ***@***.***>
Cc: Danny Gershman ***@***.***>, Your activity ***@***.***>
Subject: Re: [defenseunicorns/zarf] Zarf Repo transfer doesn't support branches (Issue #1370)

#1613<https://github.com/defenseunicorns/zarf/pull/1613> did not fix the issue. I worked around no branch support by forking BB from Github and then using repo and a tag I cut myself. Branches do not seem to work for me.
